<a href="https://colab.research.google.com/github/ferdouszislam/pytorch-practice/blob/main/CrossEntropyFalseError.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import torch

In [54]:
def softmax(x):
  exp_x = torch.exp(x)
  sum_x = torch.sum(exp_x, dim=1, keepdim=True)
  return exp_x/sum_x

def log_softmax(x):
  return torch.log(torch.exp(x) / torch.sum(torch.exp(x), dim=1, keepdim=True))

def cross_entropy_false_error(outputs, targets):
  print(outputs, targets)

  num_examples = targets.shape[0]
  batch_size = outputs.shape[0]
  outputs = log_softmax(outputs)
  outputs = outputs[range(batch_size), targets]
  outputs = -1 * outputs

  all_zeroes = torch.zeros_like(labels)
  all_ones = torch.ones_like(labels)

  label_tensor = torch.full(labels.size(), 0)
  class0_pos_mul_tensors = torch.where(labels == label_tensor, all_ones, all_zeroes)
  class0_pos_cnt = labels.eq(label_tensor).sum().item()
  class0_neg_mul_tensors = torch.where(labels != label_tensor, all_ones, all_zeroes)
  class0_neg_cnt = labels.ne(label_tensor).sum().item()

  label_tensor = torch.full(labels.size(), 1)
  class1_pos_mul_tensors = torch.where(labels == label_tensor, all_ones, all_zeroes)
  class1_pos_cnt = labels.eq(label_tensor).sum().item()
  class1_neg_mul_tensors = torch.where(labels != label_tensor, all_ones, all_zeroes)
  class1_neg_cnt = labels.ne(label_tensor).sum().item()

  label_tensor = torch.full(labels.size(), 2)
  class2_pos_mul_tensors = torch.where(labels == label_tensor, all_ones, all_zeroes)
  class2_pos_cnt = labels.eq(label_tensor).sum().item()
  class2_neg_mul_tensors = torch.where(labels != label_tensor, all_ones, all_zeroes)
  class2_neg_cnt = labels.ne(label_tensor).sum().item()

  label_tensor = torch.full(labels.size(), 3)
  class3_pos_mul_tensors = torch.where(labels == label_tensor, all_ones, all_zeroes)
  class3_pos_cnt = labels.eq(label_tensor).sum().item()
  class3_neg_mul_tensors = torch.where(labels != label_tensor, all_ones, all_zeroes)
  class3_neg_cnt = labels.ne(label_tensor).sum().item()

  print(labels)

  label_tensor = torch.full(labels.size(), 4)
  class4_pos_mul_tensors = torch.where(labels == label_tensor, all_ones, all_zeroes)
  class4_pos_cnt = labels.eq(label_tensor).sum().item()
  class4_neg_mul_tensors = torch.where(labels != label_tensor, all_ones, all_zeroes)
  class4_neg_cnt = labels.ne(label_tensor).sum().item()

  print('\nclass 4:')
  print(label_tensor)
  print(class4_pos_mul_tensors)
  print(class4_pos_cnt)
  print(class4_neg_mul_tensors)
  print(class4_neg_cnt)

  error_sum = (torch.sum(outputs*class0_pos_mul_tensors)/class0_pos_cnt) + (torch.sum(outputs*class0_neg_mul_tensors)/class0_neg_cnt) \
              + (torch.sum(outputs*class1_pos_mul_tensors)/class1_pos_cnt) + (torch.sum(outputs*class1_neg_mul_tensors)/class1_neg_cnt) \
              + (torch.sum(outputs*class2_pos_mul_tensors)/class2_pos_cnt) + (torch.sum(outputs*class2_neg_mul_tensors)/class2_neg_cnt) \
              + (torch.sum(outputs*class3_pos_mul_tensors)/class3_pos_cnt) + (torch.sum(outputs*class3_neg_mul_tensors)/class3_neg_cnt) \
              + (torch.sum(outputs*class4_pos_mul_tensors)/class4_pos_cnt) + (torch.sum(outputs*class4_neg_mul_tensors)/class4_neg_cnt) \
  
  return error_sum / 5

In [55]:
outputs = torch.tensor([[0, 1, 2, 3, 4, 2, 0, 3, 4, 1]])
labels = torch.tensor([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

cross_entropy_false_error(outputs, labels)

tensor([[0, 1, 2, 3, 4, 2, 0, 3, 4, 1]]) tensor([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])
tensor([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]])

class 4:
tensor([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])
tensor([[0, 0, 0, 0, 1, 0, 0, 0, 0, 1]])
2
tensor([[1, 1, 1, 1, 0, 1, 1, 1, 1, 0]])
8


tensor(6.2901)

In [52]:
label_tensor = torch.full(labels.size(), 4)
#labels.eq(label_tensor).sum()

class4_pos_mul_tensors = torch.where(labels == label_tensor, torch.ones_like(labels), torch.zeros_like(labels))
class4_neg_mul_tensors = torch.where(labels != label_tensor, torch.ones_like(labels), torch.zeros_like(labels))

print(labels, class4_pos_mul_tensors, class4_neg_mul_tensors)

tensor([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]]) tensor([[0, 0, 0, 0, 1, 0, 0, 0, 0, 1]]) tensor([[1, 1, 1, 1, 0, 1, 1, 1, 1, 0]])
